### ISSUE TITLE
Support column limit

### ISSUE THREAD

**Issue by kgallaha** [grochocki/XamlMagic#12]
I'd like a Hard Column Limit added to the Attribute Formatting section.  It would usually be set to 80 - 120 which represents the limits typically set when formatting C#.

This limit would force attributes to be broken onto separate lines (assuming they were originally within an attribute tolerance >1), followed by enforcement of the Max Attributes Per Line rule.  This would prevent attributes from trailing off the visible area of editors (thus requiring horizontal scrolling) while still allowing for an attribute tolerance greater than 1 (in the event there are several short attributes which could fit within the column limit).

Since the Characters Per Line limit doesn't include indentation and requires Max Attributes Per Line >1 it serves a different (somewhat niche) purpose.  It doesn't prevent code from trailing off the screen and requires you to set the Max Attributes Per Line at 2 or more.  This isn't optimal as described here:  #9

**Comment by grochocki** [comment]
In my experiences, markup languages, like XAML, do not lend well to hard column limits due to how between nested elements and long bindings, it becomes easy to hit the limit, while it is not as easy to spit the line. This is why, in my opinion, #9 makes more sense, as it achieves the idea of a column limit in the context of XAML.

At the same time, I can see how a hard column limit makes sense. That being said, how would you propose a line like this gets formatted, which in itself is 129 characters long not including any indentation:

Visibility="{x:Bind viewModel.Collection.Item.IsExpanded, Covnerter={StaticResource BooleanToVisibilityConverter}, Mode=OneWay}"

**Comment by kgallaha** [comment]
My main desire for XAML elements is to have them reside on a single line until they leave the visible area (break a column limit) in which case I want all of the attributes on separate lines.

In the event one attribute breaks the column limit then I wouldn't worry about trying to introduce any line breaks inside of it - I imagine this could get messy very quickly.  This is the simple solution and would be the least confusing to users as a single setting.  

If you'd like to include a checkbox to wrap long attributes as well then I imagine someone might appreciate it.  I don't know how much extra work would go into that (considering all the edge cases) and would be plenty happy with just to first option.  It would be further complicated if someone wanted splitting on commas and/or spaces.

**Comment by grochocki** [comment]
Got it. Thanks for the clarification. This was actually the intent behind #9. Will close that issue to this one, as this explains the feature a bit clearer.

**Comment by grochocki** [comment]
I am in the process of backporting features and bug fixes as well as transitioning issues to [Xavalon/XamlStyler](https://github.com/Xavalon/XamlStyler/issues). I already transferred this issue as a feature request.
